valid_command_prefixes = [
    "i want to go to",
    "go to",
    "i want to find",
    "find",
    "where is",
    "where's",
    "locate",
    "i want to locate",
    "show me",
    "i want to see",
    "take me to",
    "i want to see",
    "i want to know where",
    "i want to know where's",
    "i want to know where is",
    "i want to know where the",
    "i want to know where's the",
    "i want to know where is the",
    "bring me to",
    "i want to be taken to",
    "i want to be brought to",
    "take me to",
    "give me directions to",
    "lead me to",
    "show me the way to",
    
]